apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-api-config
  namespace: fcgames
data:
  jwt-issuer: "AppFiapFcGames"
  rabbitmq-host: "rabbitmq"
  aspnetcore-urls: "http://+:5002"
  dynamodb-service-url: "http://dynamodb-local:8000"
  dynamodb-region: "us-east-1"
